F90 = mpif90
F90FLAGS = -c
LFLAGS = -o
SRC = laplace.f90

ALL: laplace

laplace: laplace.o REAL_KIND_MOD.o PROBLEM_DIMS_MOD.o BOUNDRY_COND_MOD.o DOMAIN_DECOMP_MOD.o
	$(F90) $(LFLAGS) laplace laplace.o REAL_KIND_MOD.o PROBLEM_DIMS_MOD.o BOUNDRY_COND_MOD.o DOMAIN_DECOMP_MOD.o

laplace.o: laplace.f90 REAL_KIND_MOD.o PROBLEM_DIMS_MOD.o BOUNDRY_COND_MOD.o DOMAIN_DECOMP_MOD.o
	$(F90) $(F90FLAGS) laplace.f90  

REAL_KIND_MOD.o: REAL_KIND_MOD.f90
	$(F90) $(F90FLAGS) REAL_KIND_MOD.f90

PROBLEM_DIMS_MOD.o: PROBLEM_DIMS_MOD.f90
	$(F90) $(F90FLAGS) PROBLEM_DIMS_MOD.f90

BOUNDRY_COND_MOD.o: BOUNDRY_COND_MOD.f90
	$(F90) $(F90FLAGS) BOUNDRY_COND_MOD.f90

DOMAIN_DECOMP_MOD.o: DOMAIN_DECOMP_MOD.f90
	$(F90) $(F90FLAGS) DOMAIN_DECOMP_MOD.f90

clean:
	/bin/rm  *.o *.mod

cleaner:
	/bin/rm laplace *.o *.mod
